export const PRODUCT_SPEC_ICONS = [
  { value: "signal", label: "Señal / 4G" },
  { value: "battery", label: "Batería" },
  { value: "shield", label: "Seguridad" },
  { value: "platform", label: "Plataforma / móvil" },
  { value: "camera", label: "Cámara" },
  { value: "ai", label: "Inteligencia artificial" },
  { value: "storage", label: "Almacenamiento" },
  { value: "night", label: "Visión nocturna" },
  { value: "precision", label: "Precisión" },
  { value: "ultrasonic", label: "Ultrasónico" },
  { value: "tank", label: "Tanque" },
  { value: "report", label: "Reportes" },
  { value: "magnet", label: "Magnético" },
  { value: "wireless", label: "Inalámbrico" },
  { value: "alert", label: "Alertas" },
  { value: "sos", label: "SOS / emergencia" },
  { value: "gps", label: "GPS" },
  { value: "silent", label: "Silencioso" },
  { value: "waterproof", label: "Impermeable" },
] as const;
